use_frameworks!

target 'GTTexture-RxExtension_Example' do
  pod 'GTTexture-RxExtension', :path => '../'

  target 'GTTexture-RxExtension_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
