use_frameworks!

target 'GTTexture-RxExtension_Example' do
  pod 'GTTexture-RxExtension', :path => '../'

  target 'GTTexture-RxExtension_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest', '~> 4.0'
  end
end
